### ISSUE TITLE
TavilyWebSearch doesn't work

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/plugin-langchain#326]
### Describe the issue

Fails with the same error using Gemini and OpenAI as chat providers.

Reproducer:

```yaml
id: 03_rag_with_websearch_content_retriever
namespace: zoomcamp

tasks:
  - id: chat_with_rag_and_websearch_content_retriever
    type: io.kestra.plugin.ai.rag.ChatCompletion
    chatProvider:
      type: io.kestra.plugin.ai.provider.GoogleGemini
      modelName: gemini-2.5-flash
      apiKey: "{{ secret('GEMINI_API_KEY') }}"
    contentRetrievers:
      - type: io.kestra.plugin.ai.retriever.TavilyWebSearch
        apiKey: "{{ secret('TAVILY_API_KEY') }}"
    systemMessage: You are a helpful assistant that can answer questions about Kestra.
    prompt: What is the latest release of Kestra?
```

```
loader constraint violation for class retrofit2.OkHttpCall$NoContentResponseBody: when selecting overriding method 'okio.BufferedSource retrofit2.OkHttpCall$NoContentResponseBody.source()' the class loader io.kestra.core.plugins.PluginClassLoader @4f5bfbca of the selected method's type retrofit2.OkHttpCall$NoContentResponseBody, and the class loader 'app' for its super type okhttp3.ResponseBody have different Class objects for the type okio.BufferedSource used in the signature (retrofit2.OkHttpCall$NoContentResponseBody is in unnamed module of loader io.kestra.core.plugins.PluginClassLoader @4f5bfbca, parent loader 'app'; okhttp3.ResponseBody is in unnamed module of loader 'app')
```

```
TRACE 2026-05-29T11:27:31.480647Z java.lang.LinkageError: loader constraint violation for class retrofit2.OkHttpCall$NoContentResponseBody: when selecting overriding method 'okio.BufferedSource retrofit2.OkHttpCall$NoContentResponseBody.source()' the class loader io.kestra.core.plugins.PluginClassLoader @30f2d8eb of the selected method's type retrofit2.OkHttpCall$NoContentResponseBody, and the class loader 'app' for its super type okhttp3.ResponseBody have different Class objects for the type okio.BufferedSource used in the signature (retrofit2.OkHttpCall$NoContentResponseBody is in unnamed module of loader io.kestra.core.plugins.PluginClassLoader @30f2d8eb, parent loader 'app'; okhttp3.ResponseBody is in unnamed module of loader 'app')
    at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:221)
    at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
    at dev.langchain4j.web.search.tavily.TavilyClient.search(TavilyClient.java:52)
    at dev.langchain4j.web.search.tavily.TavilyWebSearchEngine.search(TavilyWebSearchEngine.java:83)
    at dev.langchain4j.rag.content.retriever.WebSearchContentRetriever.retrieve(WebSearchContentRetriever.java:45)
    at dev.langchain4j.rag.DefaultRetrievalAugmentor.process(DefaultRetrievalAugmentor.java:168)
    at dev.langchain4j.rag.DefaultRetrievalAugmentor.augment(DefaultRetrievalAugmentor.java:150)
    at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:205)
    at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:155)
    at io.kestra.plugin.ai.rag.$Proxy174.chat(Unknown Source)
    at io.kestra.plugin.ai.rag.ChatCompletion.run(ChatCompletion.java:389)
    at io.kestra.plugin.ai.rag.ChatCompletion.run(ChatCompletion.java:46)
    at io.kestra.worker.WorkerTaskCallable.doCall(WorkerTaskCallable.java:83)
    at io.kestra.worker.AbstractWorkerCallable.call(AbstractWorkerCallable.java:66)
    at io.kestra.worker.WorkerSecurityService.callInSecurityContext(WorkerSecurityService.java:11)
    at io.kestra.worker.DefaultWorker.lambda$callJob$0(DefaultWorker.java:1023)
    at io.kestra.core.trace.NoopTracer.inCurrentContext(NoopTracer.java:16)
    at io.kestra.worker.DefaultWorker.callJob(DefaultWorker.java:1019)
    at io.kestra.worker.DefaultWorker.runAttempt(DefaultWorker.java:957)
    at io.kestra.worker.DefaultWorker.run(DefaultWorker.java:743)
    at io.kestra.worker.DefaultWorker.handleTask(DefaultWorker.java:378)
    at io.kestra.worker.DefaultWorker.lambda$run$8(DefaultWorker.java:296)
    at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
```

### Environment

- Kestra Version: develop

**Comment by fdelbrayelle** [comment]
## Implementation Plan

### Design

**Root cause**: The `langchain4j-web-search-engine-tavily` library pulls in `retrofit2:2.9.0`, which in turn depends on `okhttp3` and `okio`. The shadow (fat) jar bundles `okhttp3:4.12.0` and `okio:3.15.0`. At runtime the Kestra `PluginClassLoader` delegates to the **app** (parent) classloader for `okhttp3.ResponseBody`, but keeps the plugin jar's copy of `okio.BufferedSource` for class resolution inside `retrofit2.OkHttpCall$NoContentResponseBody`. Because the app's and the plugin's `okio.BufferedSource` are different class objects (different classloader instances), the JVM raises a `LinkageError` — loader constraint violation — when it verifies the override signature.

Additionally, `opentelemetry-exporter-sender-okhttp:1.54.1` brings in `com.squareup.okhttp3:okhttp-jvm:5.1.0` (a different Maven artifact with the same Java package `okhttp3.*`), which can silently overwrite okhttp3 4.x classes inside the shadow jar merge — further exacerbating the mismatch.

**Approach**: Exclude `okhttp3/**` and `okio/**` from the shadow jar output, exactly as `com/fasterxml/jackson/**` is already excluded. This removes both libraries from the bundled artifact so the plugin classloader always resolves them from the parent (app) classloader. `retrofit2` (not present in the app) remains bundled, but since it will now find `okhttp3` and `okio` consistently from a single classloader, the constraint violation disappears.

This also eliminates the okhttp3 4.x / 5.x class-merge ambiguity for the OpenTelemetry exporter.

Workers AI (`langchain4j-workers-ai`) is the only other consumer of `retrofit2` in the dependency graph and benefits from the same fix.

### Tasks

1. **`build.gradle` — `shadowJar` block**: add two exclusions alongside the existing `com/fasterxml/jackson/**` exclusion:
   ```groovy
   exclude "okhttp3/**"
   exclude "okio/**"
   ```
2. **Verify the fix locally**: run `./gradlew shadowJar` and inspect the resulting jar with `jar tf build/libs/*.jar | grep okhttp3` to confirm no okhttp3 classes remain in the artifact.
3. **Add a unit test** for `TavilyWebSearch` retriever using WireMock (already a test dependency) to stub the Tavily HTTP endpoint and assert that `contentRetriever(runContext).retrieve(query)` returns expected content — this will catch any future regression at the classloader level without requiring a live API key.
4. **Validate** that the shadow jar exclusion does not break existing providers (OpenAI, Google Gemini, Workers AI) by checking that their integration tests still pass (or at minimum compile).

### Edge Cases

- **App classloader missing okhttp3**: If a future Kestra version removes okhttp3 from the app classpath, the plugin would fail with `ClassNotFoundException` instead of `LinkageError`. Mitigation: the Kestra platform BOM currently pins `okhttp3:4.12.0` globally; this is unlikely to disappear.
- **okio relocation alternative**: If the exclude approach causes unexpected issues (e.g. `NoClassDefFoundError` for any okio class in a specific environment), the fallback is to add explicit relocations in the shadow jar:
  ```groovy
  relocate 'retrofit2', 'io.kestra.shaded.retrofit2'
  relocate 'okhttp3', 'io.kestra.shaded.okhttp3'
  relocate 'okio', 'io.kestra.shaded.okio'
  ```
  This creates a fully isolated copy and removes the dependency on the parent having these libraries.
- **Workers AI provider**: Also uses `retrofit2` + `okhttp3`. The fix covers it automatically; no separate change needed.
- **Multiple okhttp3 artifacts** (`okhttp:4.12.0` from langchain4j + `okhttp-jvm:5.1.0` from OpenTelemetry): excluding both resolves the class-merge conflict in the shadow jar.

### Docs Impact

None. The Tavily task/retriever API and configuration properties are unchanged. The fix is purely a build-level classloader isolation change.

### Out of Scope

- Upgrading `retrofit2` to a version that natively targets `okhttp3:4.x` or `5.x` (tracked separately if needed).
- Fixing or reporting the issue upstream in `langchain4j-web-search-engine-tavily`.
- Changing the Tavily HTTP client implementation away from retrofit2.

---
> Generated by `/kestra-plugin-plan`. To proceed with implementation, comment `/plan-approved` on this issue.

**Comment by wrussell1999** [comment]
This worked on 1.3.3 but broke on 1.3.5 (no 1.3.4 image) FYI

**Comment by wrussell1999** [comment]
This works on EE 1.3.20 with the AI plugin version 1.12.6. Let's make sure this gets added to the next bug fix release so it appears in 1.3.21 for OSS. I will pin the version for the zoomcamp to that too.
